### ISSUE TITLE
upstream 1.26.0

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/php56u-twig#1]
Currently IUS has Twig 1.25.0 in our stable repositories.  Version 1.26.0 has been released upstream.  We built this new version, and it is currently available in our testing repositories.  However, Remi Collet gave us a heads up that this new version had a conflict with the version of Symfony in EPEL.  The breakage was fixed in Symfony 2.8.12.  EPEL7 was updated to this new version of Symfony, but EPEL6 was not.  We have a few options on how to proceed.

### continue to update php56u-twig regardless of EPEL's php-symfony

IUS does not package Symfony, and makes no guarantees that our packages work with everything in EPEL.  In addition, you can use Twig without Symfony.  We could publish the update for php56u-twig-1.26.0-1 on both EL6 and EL7.  EL6 users that experience a conflict can exclude php56u-twig from updates, or migrate to EL7 to get the newer Symfony from EPEL7.  The user experience here is obviously not ideal.

### stop updating php56u-twig

To keep things in sync between EL6 and EL7, we could choose to just stop updating php56u-twig entirely.  It could remain the repo, but it would be effectively unmaintained.

### stop updating php56u-twig for EL6, but continue with updates for EL7

Since this problem now only affects EL6 with the older Symfony in EPEL6, we could just stop publishing updates for EL6, and continue to maintain and update the package for EL7.

Related links:
* https://github.com/symfony/symfony/issues/20136
* https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-b589985da2
* https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-c5b86c9ec1

**Comment by carlwgeorge** [comment]
Just going to ping a few possibly interested people for feedback, based on the discussion in the [original wishlist request](https://github.com/iuscommunity/wishlist/issues/27).

@remicollet @iler @james-nesbitt @jcnventura @operinko

**Comment by remicollet** [comment]
Because of this breakage, I unpushed 1.26 from epel-6-testing (backporting fix to old symfony is still possible, but a huge work, and not planed)

More new version 1.27 breaks API again (so twig-extensions and symfony... again... fixed in symfony 2.8.13)
So, for now, only updated in fedora rawhide (not in any stable branch nor epel).

IMHO, breaking symfony is a bad thing, this is not a single application, but a big framework used by lot of applications (ex: owncloud). so will be better to keep version in sync with EPEL one.

@siwinski for information.

**Comment by b-harper** [comment]
@remicollet, as always, thanks for the information.  

Out of these three choices, I do not feel there is one that is clearly the best option.  All of them have some pros and cons.  Currently, I am leaning toward the third option.

**Comment by iler** [comment]
Our interest is more on the EL7 side so we would also be leaning toward the third option.

**Comment by troyengel** [comment]
The third option seems the most logical choice - don't make EL7 users pay for an EL6 problem, handle them as different build workstreams. $0.02!

**Comment by carlwgeorge** [comment]
Thanks everyone for the feedback.  We'll proceed with the third option.  EL6 will stay at [1.25.0-1.ius](https://github.com/iuscommunity-pkg/php56u-twig/releases/tag/1.25.0-1.ius).  EL7 is currently at [1.25.0-1.ius](https://github.com/iuscommunity-pkg/php56u-twig/releases/tag/1.25.0-1.ius), but [1.27.0-1.ius](https://github.com/iuscommunity-pkg/php56u-twig/releases/tag/1.27.0-1.ius) is pending in testing.
